= OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 2: JSON Encoding Standard version 1.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies the conformance of the implementation
under test (IUT) with respect to https://docs.ogc.org/is/24-006r1/24-006r1.html[OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 2: JSON Encoding Standard, version 1.0.0] . Conformance testing is a kind of "black box" testing that examines the
externally visible characteristics or behaviors of the IUT while disregarding
any implementation details.


Several conformance classes are defined in the Standard; the ones
listed below are covered by this test suite:

* AI_TrainingDataset
* AI_TrainingData
* AI_Task
* AI_Label
* AI_DataQuality
* AI_Labeling
* AI_TDChangeset

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. https://docs.ogc.org/is/24-006r1/24-006r1.html[OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 2: JSON Encoding Standard, version 1.0.0]


== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.trainingdmlai10part2`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Conformance Level 1
|org.opengis.cite.trainingdmlai10part2.level1.*

|Conformance Level 2
|org.opengis.cite.trainingdmlai10part2.level2.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|===
